### ISSUE TITLE
Build of v2.4.5 fails on the *-upgrade port

### ISSUE THREAD

**Issue by lasercycle** [Augustin-FL/building-pfsense-iso-from-source#13]
Followed the directions, but the [whatevername]-upgrade port will always fail, citing a missing file or directory. As a test, I edited the Makefile to change the pfSense references there, which allowed it to compile, but then it breaks the dependent ports (sysutils/*-repo and security/*-2.4.5.a.20191217.0825). There may have been something changed between when you ran your test and the 2.4.5 code. Might need some tweaks to that section as I can't find an easy solution....currently it appears as though there's a few dozen edits needed to those 3 ports to make it work.

**Comment by Augustin-FL** [comment]
I'm seeing that you created a new branch in your FreeBSD-ports fork

```
# The branch of FreeBSD ports to build is set automatically based on pfSense GUI branch.
# If you would like to build a specific branch of FreeBSD ports, the variable to set is POUDRIERE_PORTS_GIT_BRANCH
```

Could you confirm that you have set this variable in your own build.conf ?

**Comment by lasercycle** [comment]
I can confirm that POUDRIERE_PORTS_GIT_BRANCH is set. I even recreated everything from scratch, in case I'd missed a step in the instructions, but it continues to fail on that specific port. Today, I tried with v2.5 (in case it was a 2.4.5 issue) and had the exact same failure. Log file attached. It keeps saying files are not found.

[pfSense-upgrade-0.69.log](https://github.com/Augustin-FL/building-pfsense-iso-from-source/files/3979116/pfSense-upgrade-0.69.log)

**Comment by lasercycle** [comment]
Minor update, but no resolution yet. Today I tried building 2.4.5 with the original branch, but using your directions. If I _DO_ rename the directory pfSense-upgrade, it fails during port build. If I _DO NOT_ rename the directory pfSense-upgrade, it fails during ISO build. 

Variables set:
FREEBSD_BRANCH=RELENG_2_4_5
POUDRIERE_PORTS_GIT_BRANCH=RELENG_2_4_5

ISO build failure looks a lot like the port failure:
>>> Cloning everything to /root/pfsense/tmp/stage-dir staging area...mv: rename /root/pfsense/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /root/pfsense/tmp/stage-dir/usr/local/sbin/LCSecure-upgrade: No such file or directory
>>> ERROR: It was not possible to find pkg conf template /root/pfsense/tools/templates/pkg_repos/LCSecure-repo-245.conf

**Comment by Augustin-FL** [comment]
Okay,
I investigated a bit
It seems that there is 3 different errors here :

1. you are right about "pfSense-update" folder. It should NOT be renamed. This is my mistake...thanks for pointing it to me. I will update the guidelines.
2. The error ```mv: rename /root/pfsense/tmp/stage-dir/usr/local/sbin/pfSense-upgrade to /root/pfsense/tmp/stage-dir/usr/local/sbin/LCSecure-upgrade: No such file or directory``` is not critical at all. 
This error happens because you tried to compile the ```stable``` version of pfSense. It come from a ```mv``` that should not be here. I made a pull request for removing this useless mv, meaning you should not face this error in development : https://github.com/pfsense/pfsense/pull/4108

3. When building the ISO using your branches, i got the same issue as you (but in a different form): the port LCSecure-repo-{datetime} was failing because of ```pfSense-repo-245.conf: No such file or directory```.
This error is actually due to the recent changes in the development version : it seems that Netgate changed their plan for pfSense 2.4.5/2.5.0 few days ago...A new config for this has been "half deployed" in github for staging builds.
This issue can be resolved by copying the ```-245.conf``` and ```-245.descr``` files from [here](https://github.com/pfsense/pfsense/tree/master/tools/templates/pkg_repos) to [here](https://github.com/pfsense/FreeBSD-ports/tree/devel/sysutils/pfSense-repo/files). Both files should have their original names (```pfSense-repo-245.conf``` and ```pfSense-repo-245.descr```) in the destination folder.


I also run through a fourth issue when building the ISO: I couldn't install packages on top of my ISO because the name of FreeBSD branch is partially hardcoded in pfSense PKG configuration (```>>> Installing built ports (packages) in chroot (/root/pfsense/tmp/stage-dir)... Failed!```). 
In order to fix the error, i had to go [to update this line](https://github.com/pfsense/pfsense/blob/master/tools/templates/pkg_repos/pfSense-repo-devel.conf#L12). I replaced ```_%REPO_BRANCH_PREFIX%%devel``` by ```_LC_1_0_0```.

I was able to build an ISO of LCSecure after resolving these issues.

Could you try that and tell me if it is also working for you ?

**Comment by lasercycle** [comment]
That fixed the original issues, but led to new ones. Management has flagged pfSense as being more trouble than it's worth with the sketchy ability to compile the public code, so I think we're probably stepping away from testing it. I appreciate all your help! Last round of 3 errors we got were as follows. Strangely, none of these were an issue previously, so I may have done something wrong on our last attempt, but I wanted to pass them along just in case others run into the same things.

sysutils/blinkled: "'sys/ck.h' file not found"
archivers/libmspack: "Couldn't fetch this"
devel/vstr: "Couldn't fetch this"

Thanks again for all your help!

**Comment by LCHOICEzz** [comment]
So whether I should change the names of 
![image](https://user-images.githubusercontent.com/21484379/72399960-aadb5b00-3782-11ea-847b-d4f58e506462.png)
to libreSense-repo-245.conf and libreSense-repo-245.descr
