### ISSUE TITLE
powerpc build

### ISSUE THREAD

**Issue by ghost** [Augustin-FL/building-pfsense-iso-from-source#28]
Can we build it for the powerpc platform, particularly the QorIQ P2020?

**Comment by ghost** [comment]
Any updates on this?

**Comment by Augustin-FL** [comment]
Hi,

No sry...i don't have a clue on that :( 

The architecture that pfSense will be built for...is defined by `uname -m`. So if you want to build an ISO for powerPC architecture, then you'll need a server with powerPC architecture. 

...It seems possible to build ports for a specific architecture however:

The target architecture for ports is defined by an environment variable (DEFAULT_ARCH_LIST) and is checked by a function named [```poudriere_possible_archs```](
https://github.com/pfsense/pfsense/blob/master/tools/builder_common.sh#L1481). Netgate seems to have implemented the possibility to build ports for a different target architecture than the server itself, using KVM-QEMU.
(I guess it's because they are building ARM ports on their x64 build servers?). 
Only `qemu-arm-static` is currently used, but you could probably use `qemu-ppc64-static` aswell.

Maybe you could try to build the ISO and past the the results here/submit a Pull request to the original pfSense repo with your updates ?
