### ISSUE TITLE
./build.sh --update-pkg-repo Error snort not found 

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#30]
Dear Augustine,

### Please help to solve the below issue. 

=> snort-2.9.16.tar.gz doesn't seem to exist in /portdistfiles/.
=> Attempting to fetch https://snort.org/downloads/snort/snort-2.9.16.tar.gz
**fetch: https://snort.org/downloads/snort/snort-2.9.16.tar.gz: Not Found**
=> Attempting to fetch https://mirrors.rit.edu/zi/snort-2.9.16.tar.gz
**fetch: https://mirrors.rit.edu/zi/snort-2.9.16.tar.gz: Not Found**
=> Attempting to fetch https://www.zi0r.com/mirrors/snort-2.9.16.tar.gz
**fetch: https://www.zi0r.com/mirrors/snort-2.9.16.tar.gz: Not Found**
=> Attempting to fetch http://distcache.FreeBSD.org/local-distfiles/zi/snort-2.9.16.tar.gz
**fetch: http://distcache.FreeBSD.org/local-distfiles/zi/snort-2.9.16.tar.gz: Not Found**
=> Attempting to fetch http://distcache.us-east.FreeBSD.org/local-distfiles/zi/snort-2.9.16.tar.gz
**fetch: http://distcache.us-east.FreeBSD.org/local-distfiles/zi/snort-2.9.16.tar.gz: Not Found**
=> Attempting to fetch http://distcache.eu.FreeBSD.org/local-distfiles/zi/snort-2.9.16.tar.gz
**fetch: http://distcache.eu.FreeBSD.org/local-distfiles/zi/snort-2.9.16.tar.gz: Not Found**
=> Attempting to fetch http://distcache.us-west.FreeBSD.org/local-distfiles/zi/snort-2.9.16.tar.gz
**fetch: http://distcache.us-west.FreeBSD.org/local-distfiles/zi/snort-2.9.16.tar.gz: Not Found**
=> Attempting to fetch http://distcache.FreeBSD.org/ports-distfiles/snort-2.9.16.tar.gz
**fetch: http://distcache.FreeBSD.org/ports-distfiles/snort-2.9.16.tar.gz: Not Found**
=> Couldn't fetch it - please try to retrieve this
=> port manually into /portdistfiles/ and try again.
*** Error code 1

Stop.
make: stopped in /usr/ports/security/snort
=>> Cleaning up wrkdir
===>  Cleaning for snort-2.9.16
build of security/snort | snort-2.9.16 ended at Thu Aug 20 21:03:59 IST 2020
build time: 00:00:30
!!! build failure encountered !!!

**Comment by sreekumarpm** [comment]
Dear Augustin,

https://snort.org/downloads/snort/snort-2.9.16.tar.gz  this link is not valid new link is 
https://snort.org/downloads/snort/snort-2.9.16.1.tar.gz 

Please update accordingly.

**Comment by Augustin-FL** [comment]
Hi,

I believe you are getting this error because your port repo is not in sync with  pfsense's ports repo.


Netgate synchronized their own repo with official FreeBSD ports 2 days ago ( in https://github.com/pfsense/FreeBSD-ports/commit/17d9ea41b4cd036a39238c9f79add64f50cc580a ). Could you make sure your fork is up to date?

also...for information it seems that netgate is using FreeBSD 12.1 now. (https://github.com/pfsense/docs/commit/3d2f773a39fecbdbedd882f7bfb1ec45162a0386 ). maybe that's also part of the reason why you're getting this error?

**Comment by sreekupm** [comment]
Dear Augustin,

Same Error, 
Please check I think its not updated.

**Comment by sreekupm** [comment]
Dear Augustin,

Please check the file 
https://github.com/pfsense/FreeBSD-ports/blob/devel/security/snort/Makefile
**PORTVERSION=	2.9.16**

also check Snort Site 

https://snort.org/downloads/

please do a pull request and change accordingly

**Comment by Augustin-FL** [comment]
12.2 doesn't fix the issue. Re-opening ..

**Comment by Augustin-FL** [comment]
Its seems like the synchronization issue between NetGate & FreeBSD [I explained here ](https://github.com/Augustin-FL/building-pfsense-iso-from-source#if-your-encounter-errors-during-ports-or-kernel-build-possible-root-causes-and-how-to-fix-them)

- In August then in September, snort devs decided to release two new versions (config bump+distfile update). At this time of writing, the current version is [2.9.16.1](https://svnweb.freebsd.org/ports/head/security/snort/Makefile?revision=547272&view=markup) and the new  tar.gz URL is http://distcache.freebsd.org/ports-distfiles/snort-2.9.16-1.tar.gz
- But, NetGate didn't refresh their own Makefile. Which means that any attempt to build this port will now fail.
- It is fine for NetGate, because they have built the port on their internal server in April. But it's not fine for you ...

The recommended way to fix this issue is to synchronize your FreeBSD ports with [the official FreeBSD ports repository](https://github.com/freebsd/freebsd-ports). Or, to disable snort build.

**Comment by Augustin-FL** [comment]
This issue should be fixed by https://github.com/pfsense/FreeBSD-ports/pull/933

**Comment by sreekupm** [comment]
Dear Augustin, 

I have made the below changes and built successfully 
**Makefile**
Change to PORTVERSION=	2.9.16.1

**distinfo** 
change the below accordingly 
TIMESTAMP = 1587667384
SHA256 (snort-2.9.16.1.tar.gz) = 9688d8edf1da09dec6574000fb3c0e62f99c56428587616e17c60103c0bcbad7
SIZE (snort-2.9.16.1.tar.gz) = 6947960

**Comment by Augustin-FL** [comment]
the PR has been merged. Closing the issue
