### ISSUE TITLE
Build for ARM

### ISSUE THREAD

**Issue by sreekupm** [Augustin-FL/building-pfsense-iso-from-source#34]
Dear Augustin, 

What are the changes required for ARM ?

**Comment by Augustin-FL** [comment]
Hi,

- The target architecture for building the kernel is based on [`uname -m`](https://github.com/pfsense/pfsense/blob/a68f7a3dd6e0c1bdf5ce5c8ed28da291bc8cb50f/tools/builder_common.sh#L1084) : if you want to build an ARM pfSense ISO, you will have to run an ARM FreeBSD builder.

- The target architecture for the ports is defined by an environment variable (`DEFAULT_ARCH_LIST`) and is checked by a function named [```poudriere_possible_archs```](
https://github.com/pfsense/pfsense/blob/a68f7a3dd6e0c1bdf5ce5c8ed28da291bc8cb50f/tools/builder_common.sh#L1499). Netgate has implemented the possibility to build ports for ARM on x86_64 architecture, using KVM-QEMU.

**Comment by sreekupm** [comment]
Can I build on X86 build machine?

**Comment by Augustin-FL** [comment]
The ports, yes. The kernel, no.

**Comment by sreekupm** [comment]
How we can build pfsense for ARM?

**Comment by Augustin-FL** [comment]
You need to excecute the build commands on an arm server

**Comment by Augustin-FL** [comment]
Can i close this issue?

**Comment by neo-rainboy** [comment]
I am sorry for late question,
but can't we use an emulator to build the ARM on x86 machines?

**Comment by sreekupm** [comment]
Dear Neo-rainboy, 

Please explain the process, it will help me and others.

**Comment by neo-rainboy** [comment]
It's just an assumption, I need Augustin's confirmation as well, but I assume we can emulate the whole process with QEMU

**Comment by sreekupm** [comment]
it's ok for ports, what about kernel ?

**Comment by neo-rainboy** [comment]
The same goes for kernel with cross compile tools I guess

**Comment by sreekupm** [comment]
ok thanks, can you explain the steps

**Comment by sreekupm** [comment]
@neo-rainboy 
please explain the same, it will help for me and others.

**Comment by neo-rainboy** [comment]
I will try to, but please give me at least 1-2 days to try and check the practicality of the solution as well, will update the results here, but if @Augustin-FL  confirm the solution then will try to come up with the steps as well

**Comment by sreekupm** [comment]
ok, done,
waiting for the update.

**Comment by Augustin-FL** [comment]
Hi @neo-rainboy 

I believe It's not that simple : the kernel is built inside a jail. You need (I think?) to have an ARM jail in order to build an ARM kernel.

But : BSD jail system is not a real virtual machine....It's more something like linux namespaces/Docker/LXC/etc....

[You can't have an ARM jail on an AMD64 server](https://forums.freebsd.org/threads/arm-or-sparc-in-freebsd-jail-on-amd64-host.65130/). Quoting from wikipedia : `The FreeBSD jail does not [...] achieve true virtualization; it does not allow the virtual machines to run different kernel versions than that of the base system. All virtual servers share the same kernel [...]. It is possible to use jails to safely test new software, but not new kernels.`

That said, I may be wrong : maybe you can create ARM kernel on an AMD64 jail. You will need need to tune some .sh files for that however...since Netgate never implemented this feature. I let you have a look and revert back to us ?

**Comment by sreekupm** [comment]
@neo-rainboy 
any updates?
