### ISSUE TITLE
jail newer than host 

### ISSUE THREAD

**Issue by aminbaik88** [Augustin-FL/building-pfsense-iso-from-source#37]
Hello, 
after i build the jail and  try to build the ports its give me waring that jail is newer than host.
thanks.

**Comment by Augustin-FL** [comment]
yes, that's expected.  what's the issue?

**Comment by aminbaik88** [comment]
just a warring , is there any problem in this case ? 
how to resolve in general ?

**Comment by Augustin-FL** [comment]
warnings are not here to report problems or issues (that's the job of errors)
warnings are here to ....well, to warn you. 

Here, it indicates you that you *may be* using the wrong freebsd version to build your jail. 

"*may be*" is different from "*are*"

If you are asking about why is exactly the jail newer....well I dunno.  probably because Netgate decided to upgrade the jail to a specific point of time?

**Comment by aminbaik88** [comment]
how i can make freebsd same of jail version ?

**Comment by Augustin-FL** [comment]
I'm not sure as I didn't try to do it myself

i believe there's two ways : 
- either by running freebsd-upgrade. everything is explained here : https://docs.freebsd.org/en/books/handbook/cutting-edge/
- either by compiling your own freebsd ISO at a specific commit in time. this way you would have much more control on the OS version but that is also way more complex

**Comment by Augustin-FL** [comment]
I believe my message resolves this issue?
