### ISSUE TITLE
wireguard build&rust problem 

### ISSUE THREAD

**Issue by aminbaik88** [Augustin-FL/building-pfsense-iso-from-source#39]
Hello, 
i get fail error with wireguard package ... 
i try to open the ports i see the link is : github.netgate.com 
how i can bypass that ?
also the rust package always fail i tried to remove suricata form poudriere_bulk. but its still try to build. rust i dep for suricata
Thanks.

**Comment by aminbaik88** [comment]
Hello,
i delete a suricata from poudriere_bulk and reslove the problem 
the problem is with wireguard package now can you help me ?
Thanks.

**Comment by Augustin-FL** [comment]
This issue seems related to the pfSense wireguard controversy.

wireguard-tools port was initially stored in the Negate internal Gitlab. The port has then been open sourced when 2.5.0 got released (URL : https://github.com/pfsense/wireguard-tools ). You need to change the port URL if you want to build wireguard-tools.

This port was not open source for a valid reason : it was under developpment, not ready to be used. As you may already be aware, the port (and all wireguard kernel counterpart) have eventually been removed from pfSense after some FreeBSD developpers [complained on the code quality](https://lists.zx2c4.com/pipermail/wireguard/2021-March/006494.html)....so this issue should not exist anymore.

More explanation at https://redmine.pfsense.org/issues/8786#note-26  and
https://m.youtube.com/watch?v=uGNorRLefBg

**Comment by Augustin-FL** [comment]
As for the rust problem, it is probably a RAM issue.

Rust requires a lot of RAM when being built...you probably didn't allocate enough? How many RAM are you using? 

(More info here, if needed : https://github.com/Augustin-FL/building-pfsense-iso-from-source/issues/1#issuecomment-544201630 )

**Comment by aminbaik88** [comment]
Hello, 
how i can change the port url ? 
Thanks.

**Comment by aminbaik88** [comment]
i am try to clone the github pfsense port and try ....

**Comment by aminbaik88** [comment]
Thank you.

**Comment by Augustin-FL** [comment]
You can change the port URL by updating the port files

**Comment by Augustin-FL** [comment]
Seems that I closed this issue too fast...wireguard-tools is still included in pfSense 2.5.0
I've updated the notes accordingly to exclude it.
