### ISSUE TITLE
i have modified the pfsense source code and now i want to test the new code, how to do it?

### ISSUE THREAD

**Issue by usamasiddique52** [Augustin-FL/building-pfsense-iso-from-source#41]
i have modified the pfsense source code and now i want to test the new code, how to do it?

**Comment by usamasiddique52** [comment]
Should i create the .iso file for it or there is another way to test my code?

**Comment by usamasiddique52** [comment]
Also how much time it takes to create .iso file from source code?
(My laptop specs are:
16gb ram
core i7 9-gen
1tb ssd
6gb nvidia 1660ti
)

**Comment by usamasiddique52** [comment]
And also can you please tell me what is meant by this   "Checkout to the the branch you would like to build (devel-12 for dev version, RELENG_2_5_0 for stable version)."

**Comment by Augustin-FL** [comment]
Test what new code?

If you are referring to https://github.com/usamasiddique52/pfsense/commit/c46f8863e54efb421544db2a4178e37b7b4bd518.diff , then you should use the [patch package](https://docs.netgate.com/pfsense/en/latest/development/system-patches.html) to apply apply your changes on an existing appliance instead of rebuilding an ISO?

**Comment by usamasiddique52** [comment]
Thanks alot
