### ISSUE TITLE
How can I find package in pfsense compiled by myself?

### ISSUE THREAD

**Issue by gitmessage** [Augustin-FL/building-pfsense-iso-from-source#46]
follow "building-pfsense-iso-from-source". I compile iso.
Install in vm. 
http://192.168.1.1 and login.
In "System -> SystemPackage Manager -> Available Packages" 
Unable to retrieve package information.

<img width="535" alt="package" src="https://user-images.githubusercontent.com/24708498/124607228-388f9680-dea0-11eb-80a0-b430218846fc.png">

How can I find package in pfsense compiled by myself?
Thanks!

**Comment by Augustin-FL** [comment]
That's because the IP the builder had when building the ISO...is getting hardcoded in the pfSense config files : 
`%%PKG_REPO_SERVER_RELEASE%%` in https://github.com/pfsense/pfsense/blob/master/tools/templates/pkg_repos/pfSense-repo-245.conf#L4

The pfSense build system expect the builder to be reachable at any time by the built ISO. The IP the ISO uses for contacting the build server, is the IP of the build server first network interface. As per the build.conf:
```
# This command retrieves the IP address of the first network interface
export myIPAddress=$(ifconfig -a | grep inet | head -1 | cut -d ' ' -f 2)
```

If your IP has changed in between, then you'll need to update the following file to make it point the desired location : `/usr/local/share/pfSense/pkg/repos/pfSense-repo-245.conf`

**Comment by gitmessage** [comment]
Thanks. I will try.
